services:
  database:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: join_us_mvp
      MYSQL_USER: join_us_mvp_admin
      MYSQL_PASSWORD: SN384yGAETYrwsxJd6tLcM
      MYSQL_ROOT_PASSWORD: cvJVDmP293t7KAnCNzMwSL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: join_us_mvp_admin
      PMA_PASSWORD: SN384yGAETYrwsxJd6tLcM
      