/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssociationApplicationFormModal: typeof import('./src/components/AssociationApplication/AssociationApplicationFormModal.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    CreateAssociation: typeof import('./src/components/Create/CreateAssociation.vue')['default']
    CreateEvent: typeof import('./src/components/Create/CreateEvent.vue')['default']
    CreateTypeAssociation: typeof import('./src/components/Create/CreateTypeAssociation.vue')['default']
    CreateTypeEvent: typeof import('./src/components/Create/CreateTypeEvent.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DisplayEventsMap: typeof import('./src/components/DisplayEventsMap.vue')['default']
    EventsList: typeof import('./src/components/EventsList.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GoogleAutoCompleteComponent: typeof import('./src/components/GoogleAutoCompleteComponent.vue')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputErrorMessage: typeof import('./src/components/InputErrorMessage.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JnsField: typeof import('./src/components/ui/JnsField.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewsLetters: typeof import('./src/components/NewsLetters.vue')['default']
    NotificationBanner: typeof import('./src/components/NotificationBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    UpdateAssociation: typeof import('./src/components/Update/UpdateAssociation.vue')['default']
    UpdateEvent: typeof import('./src/components/Update/UpdateEvent.vue')['default']
    UpdateTypeAssociation: typeof import('./src/components/Update/UpdateTypeAssociation.vue')['default']
    UpdateTypeEvent: typeof import('./src/components/Update/UpdateTypeEvent.vue')['default']
  }
}
